### PR TITLE
Added NQueens Implementation in Java

### PR DESCRIPTION
**Pull request by durzoflint**

### CODE REVIEW

**Comment by grufelous** [comment]
Hi @durzoflint! The commit includes some DS_Store files. Please remove the binaries and just include the Java file.

**Comment by durzoflint** [comment]
Hello @grufelous apologies for the that, have removed the file system binaries

**Comment by grufelous** [comment]
It seems like there are still some binaries left. Please add it to the `.gitignore` if not already in it.

**Comment by durzoflint** [comment]
@grufelous updated gitignore

**Pull request merged**
